/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package krilis.solver

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertEquals


class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test fun testJoiningExpressions() {
        val x = ContinuousVar("x")
        val y = ContinuousVar("y")
        val expr1: LinearExpr = x + y
        val expr2: LinearExpr = y + x
        val expr3: LinearExpr = expr1 + expr2
        assertEquals(expr1.expressionVars["x"]?.coeff, 1.0)
        assertEquals(expr2.expressionVars["y"]?.coeff, 1.0)
        assertEquals(expr3.expressionVars["x"]?.coeff, 2.0)
        assertEquals(expr3.expressionVars["y"]?.coeff, 2.0)
        assertEquals(expr1.constantSum, 0.0)
        assertEquals(expr2.constantSum, 0.0)
        assertEquals(expr3.constantSum, 0.0)
    }

    @Test fun testAddConstantsInExpressions() {
        val x = ContinuousVar("x")
        val expr1: LinearExpr = x + 4.0
        assertEquals(expr1.constantSum, 4.0)
        val expr2: LinearExpr = x + 6.0
        assertEquals((expr2 + expr1).constantSum, 10.0)
    }

    @Test fun testSubtractingExpressions() {
        val a = ContinuousVar("a")
        val b = ContinuousVar("b")
        val aMinusB: LinearExpr = a - b
        assertEquals(aMinusB.constantSum, 0.0)
        assertEquals(aMinusB.expressionVars["a"]?.coeff, 1.0)
        assertEquals(aMinusB.expressionVars["b"]?.coeff, -1.0)
    }

    @Test fun testVarsAddingConstants() {
        val a = ContinuousVar("a")
        val aPlusConst1: LinearExpr = a + 42.0
        assertEquals(aPlusConst1.constantSum, 42.0)
        val aPlusConst2: LinearExpr = 69.0 + a
        assertEquals(aPlusConst2.constantSum, 69.0)
        val constPlusA1: LinearExpr = a + 42.0
        assertEquals(constPlusA1.constantSum, 42.0)
        val constPlusA2: LinearExpr = 69.0 + a
        assertEquals(constPlusA2.constantSum, 69.0)
    }
}
